# Generated by Django 4.2.13 on 2024-06-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dosen',
            field=models.BooleanField(default=False, verbose_name='Is dosen'),
        ),
    ]
