# Generated by Django 4.2.13 on 2024-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_postnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnews',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
