# Generated by Django 4.2.13 on 2024-06-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_postnews_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangKepakaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pakar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografi', models.TextField()),
                ('minat_penelitian', models.TextField()),
                ('bidang_kepakaran', models.ManyToManyField(related_name='pakar', to='accounts.bidangkepakaran')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('social_media_ig', models.URLField(blank=True, null=True)),
                ('social_media_twitter', models.URLField(blank=True, null=True)),
                ('social_media_facebook', models.URLField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, help_text='Gambar profil', null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPenelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_riwayat', models.CharField(max_length=200)),
                ('tahun_riwayat', models.IntegerField()),
                ('deskripsi_riwayat', models.TextField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penelitian', to='accounts.pakar')),
            ],
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_publikasi', models.CharField(max_length=200)),
                ('tahun_publikasi', models.IntegerField()),
                ('link_publikasi', models.URLField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publikasi', to='accounts.pakar')),
            ],
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_penelitian', models.CharField(max_length=200)),
                ('tahun_penelitian', models.IntegerField()),
                ('deskripsi_penelitian', models.TextField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penelitian', to='accounts.pakar')),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendidikan', to='accounts.pakar')),
            ],
        ),
        migrations.CreateModel(
            name='KaryaIlmiah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_karya', models.CharField(max_length=200)),
                ('tahun_karya', models.IntegerField()),
                ('link_karya', models.URLField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karya_ilmiah', to='accounts.pakar')),
            ],
        ),
    ]
