# Generated by Django 4.2.13 on 2024-06-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
