# Generated by Django 4.2.13 on 2024-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
