# Generated by Django 4.2.13 on 2024-06-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='accounts.pakar')),
            ],
        ),
    ]
