# Generated by Django 4.2.13 on 2024-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_linkedin_user_scopus_id_user_sinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
