# Generated by Django 4.2.13 on 2024-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_google_scholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendidikan',
            name='program_studi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
