# Generated by Django 4.2.13 on 2024-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_pendidikan_program_studi'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='link_penelitian',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
