# Generated by Django 4.2.13 on 2024-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_penelitian_link_penelitian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian',
            name='deskripsi_penelitian',
        ),
        migrations.RemoveField(
            model_name='riwayatpenelitian',
            name='deskripsi_riwayat',
        ),
        migrations.AddField(
            model_name='riwayatpenelitian',
            name='link_riwayat_penelitian',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
