# Generated by Django 4.2.13 on 2024-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_penelitian_deskripsi_penelitian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyailmiah',
            name='tim_karya',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penelitian',
            name='tim_penelitian',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publikasi',
            name='tim_publikasi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riwayatpenelitian',
            name='tim_riwayat',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
