# Generated by Django 4.2.13 on 2024-06-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_karyailmiah_tim_karya_penelitian_tim_penelitian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTheNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_news', models.CharField(max_length=200)),
                ('tanggal_terbit', models.IntegerField()),
                ('link_news', models.URLField()),
                ('media', models.CharField(max_length=200)),
                ('pakar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_news', to='accounts.pakar')),
            ],
        ),
        migrations.DeleteModel(
            name='KaryaIlmiah',
        ),
    ]
