# Generated by Django 4.2.13 on 2024-06-17 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_inthenews_delete_karyailmiah'),
    ]

    operations = [
        migrations.AddField(
            model_name='inthenews',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename_image),
        ),
    ]
