# Generated by Django 4.2.13 on 2024-06-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_inthenews_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inthenews',
            name='tanggal_terbit',
            field=models.DateField(),
        ),
    ]
