# Generated by Django 4.2.13 on 2024-06-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_penelitian_category_penelitian_pengabdianan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatpenelitian',
            name='pakar',
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='category_penelitian',
            field=models.CharField(choices=[('nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Publikasi',
        ),
        migrations.DeleteModel(
            name='RiwayatPenelitian',
        ),
    ]
