# Generated by Django 4.2.13 on 2024-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_riwayatpenelitian_pakar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='judul_book',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link_book',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tahun_book',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='jabatan_organisasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='nama_organisasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='tahun_organisasi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='link_penelitian',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='tahun_penelitian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='tim_penelitian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengabdianan',
            name='judul_pengabdian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengabdianan',
            name='link_pengabdian',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengabdianan',
            name='tahun_pengabdian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengabdianan',
            name='tim_pengabdian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
