# Generated by Django 4.2.13 on 2024-06-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
