# Generated by Django 4.2.13 on 2024-06-25 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_adress_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
