# Generated by Django 4.2.13 on 2024-06-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_book_penerbit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pengabdianan',
            new_name='Pengabdian',
        ),
    ]
