# Generated by Django 4.2.13 on 2024-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_pengabdianan_pengabdian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakar',
            name='biografi',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
