# Generated by Django 4.2.13 on 2024-06-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_pakar_biografi_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pakar',
            name='minatpenelitian',
            field=models.ManyToManyField(related_name='dosen', to='accounts.tag'),
        ),
    ]
