# Generated by Django 4.2.13 on 2024-06-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_tag_pakar_minatpenelitian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakar',
            name='minatpenelitian',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
