# Generated by Django 4.2.13 on 2024-06-26 05:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('accounts', '0033_remove_pakar_minatpenelitian_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakar',
            name='minat_penelitian',
        ),
        migrations.AddField(
            model_name='pakar',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
