# Generated by Django 4.2.13 on 2024-06-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rename_programstudi_prodi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakar',
            name='prodi',
        ),
        migrations.DeleteModel(
            name='Prodi',
        ),
    ]
