# Generated by Django 4.2.13 on 2024-06-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_pakar_program_studi_pakar_program_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakar',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.programstudi'),
        ),
    ]
