# Generated by Django 4.2.13 on 2024-06-27 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_pakar_program_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakar',
            name='program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakar', to='accounts.programstudi'),
        ),
    ]
