# Generated by Django 4.2.13 on 2024-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/assets/default.jpg', upload_to='profile_pics'),
        ),
    ]
