# Generated by Django 4.2.13 on 2024-07-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakar',
            name='program_studi',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pakar', to='accounts.programstudi'),
            preserve_default=False,
        ),
    ]
