# Generated by Django 4.2.13 on 2024-07-04 16:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_pakar_program_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/assets/default.jpg', upload_to=accounts.models.rename_image),
        ),
    ]
